version: '2'

services:

  app:
      image: php:7.1.2-fpm
      expose:
          - "9000"
      volumes:
          - ./php/php.ini:/usr/local/etc/php/php.ini
          - ./app:/var/www/html

  nginx:
      image: nginx:1.10.3
      ports:
          - "8080:80"
      links:
          - app
      volumes_from:
          - app
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf